version: '3'
services:
  nginx:
    build:
      context: /home/tjimboo/ssltest/
      dockerfile: Dockerfile
    ports:
      - "443:8443"
      - "80:8080"
    network_mode: bridge
    volumes:
      - ./nginxconfig:/etc/nginx/conf.d:z
      - ./nginxlog1:/var/log/nginx:z
      - ./nginxlog2:/usr/local/var/log/nginx:z
      - ./cert:/etc/letsencrypt:z
      - ./certs-data:/etc/nginx/html:z 
